### PR TITLE
Fix issue with keyboard freezing

### LINKED ISSUE #122: Keys get stuck about an hour after firmware startup
Updated to firmware 8.3.1 and after about an hour of use following firmware startup, the actual key gets virtually stuck. I can't get it unstuck, only by power cycling the keyboard. Today, it happened to the "e" key, then Alt+Tab (via Mod+d), and finally the down arrow (via Mod+k).

This is by far the most critical bug as we can't make an upcoming release until it gets fixed.

### PR DESCRIPTION
**Pull request by Lauszus**
* Fixes #122 
* Fix PIT timer period and added functions for getting the current time in microseconds - see #127

### CODE REVIEW

**Comment by mondalaci** [comment]
@Lauszus Oops, it did it again.

Seriously though, unfortunately this fix doesn't work. The up arrow scancode just stuck after several hours of use.

**Comment by Lauszus** [comment]
I have been running the test in: https://github.com/UltimateHackingKeyboard/firmware/commit/8edc17ed094971e0e3aa1dffd4ef6c904c96384c for an hour now. So far it's rock solid :)

**Comment by mondalaci** [comment]
Awesome! :) Thanks for the hard work! Let test this for a couple of days to make sure it doesn't ever freeze.

**Comment by mondalaci** [comment]
I've just finished bisecting the Lauszus-dev branch of this repo, and found that 4214f3e0b616d0ff60c6f05d8672d84e0e00255f fixed the freeze bug.

**Comment by Lauszus** [comment]
Awesome!

**Comment by Lauszus** [comment]
I'll merge @eltang changes into this one.

**Comment by eltang** [comment]
I still have some more changes to make, after which I'll do a full test.

**Comment by Lauszus** [comment]
@eltang are they relevant to this PR or are they other fixes like the mouse scrolling issue #133?

**Comment by eltang** [comment]
Yes, there are some issues with sleep and wake right now and I am tweaking the code to make it so that it looks for changes in the key states rather than the reports.

**Comment by Lauszus** [comment]
@eltang okay great. Just let me know when you are done and I will merge it into this PR.

Assuming your second comment was an answer to the following comment: https://github.com/UltimateHackingKeyboard/firmware/commit/d3dfc9bd2c00a0f2612c8bb33a3cc8587855b1e6#commitcomment-29555490, then I will revert your revert then :)

**Comment by Lauszus** [comment]
Btw I just tried to set ```USB_BASIC_KEYBOARD_INTERRUPT_IN_INTERVAL``` to 1 and checked the output in Wireshark and it seems to work as well :)

**Comment by mondalaci** [comment]
This PR contains a lot of commits and I'm starting to get lost. I'd like to merge this the way it is and encourage other commits in other PRs.

Any objections? Also, any difference between @Lauszus branch and the Lauszus-dev branch of this repo?

**Comment by Lauszus** [comment]
I agree, best to fix the other issues in separate PR's.

No, I have merged all the changes in Lauszus-dev into this one. Most mentionable is  https://github.com/UltimateHackingKeyboard/firmware/commit/4214f3e0b616d0ff60c6f05d8672d84e0e00255f.

**Comment by mondalaci** [comment]
Any objections, @eltang? If not, I'll finally merge this.

**Comment by Lauszus** [comment]
Shouldn't we wait and test this overnight just to be 100 % sure this time?

Btw I need to remove the test code before it is merged.

**Comment by mondalaci** [comment]
Good idea. I'll test it on two machines during night.

I'd be worth to extract the test code into a separate file and #ifdef it for future testing.

**Comment by Lauszus** [comment]
I have disabled the test code in https://github.com/UltimateHackingKeyboard/firmware/pull/123/commits/5b32c0da43dcae8df6babe3b58d2b3072bd47dec. However I did not put into a separate file, as it only works at those lines in ```usb_report_updater.c``` anyway.

**Comment by mondalaci** [comment]
@Lauszus Thanks! It's fine the way it is.

**Comment by eltang** [comment]
It seems an extraneous `CurrentTime` variable got introduced somewhere along the way.

**Comment by Lauszus** [comment]
Thanks @eltang. This was due to a merge conflict in c69f664e850a224730728274a8b4b1b76698d7c2.

**Comment by mondalaci** [comment]
Excellent work, guys! Please don't add any further commits to this PR. Let's test it overnight and I'll merge it if it works at everyone's end.

**Comment by Lauszus** [comment]
I stopped the test on my computer. Everything works fine :)

**Comment by mondalaci** [comment]
I fully agree. I tested it on 2 computers for 8 hours each and it was rock stable. I'm merging this. What a wonderful way to close the previous month!

**Pull request merged**
