### PR TITLE
LEDs: Add a method to set all LEDs to a given brightness

### PR DESCRIPTION
**Pull request by algernon**
Mostly for testing purposes, but can be used later for backlight up/down stuff, too.

### CODE REVIEW

**Comment by mondalaci** [comment]
This seems redundant to me given that the brightness of the individual LEDs can already be set via USB. We expose the [LED driver](https://github.com/UltimateHackingKeyboard/datasheets/blob/9f34923269ba477a92cfdc1afd6200b6ab92a991/leds/31FL3731.pdf) of both keyboard halves by [protocol translating](https://github.com/UltimateHackingKeyboard/firmware/blob/ed0b51dbff44fed1eb7bf9cacb3535e30aed8287/right/src/usb_protocol_handler.c#L124) from USB HID to I2C, allowing for [scripting](https://github.com/UltimateHackingKeyboard/agent/blob/ffc820f47accac14fa352803be32e200cdddf881/usb/pulse-leds.js) the LEDs.

**Comment by mondalaci** [comment]
Any objections are welcome. :)

**Comment by algernon** [comment]
Yup, I know its possible via USB HID, but that's not the most convenient thing when testing changes made to how the keys are handled. Furthermore, this makes it easier to have a way to adjust the backlighting, without needing any software on the host. That's very convenient when you plug your keyboard into computers you don't control, and where you can't have additional software installed, yet, still would like to use most features.

And backlighting is a very useful feature. Something I may want to use in, say, a server room, where I'm not going to install any keyboard-related stuff on the host system. :)

**Comment by mondalaci** [comment]
Thanks for explaining, makes sense! :)

**Pull request merged**
