### PR TITLE
Trackpoint drifts

### PR DESCRIPTION
**Pull request by kareltucek**
Here is some algorithm to reset drifts... 

If you want debug info, then checkout only the first commit - then it will show "RST" on resets on the segment display.

### CODE REVIEW

**Comment by kareltucek** [comment]
Sometimes the module seems to stop responding. Not sure why.

**Comment by mondalaci** [comment]
Just started testing this. I'll get back with my findings in a day or two.

**Comment by mondalaci** [comment]
@kareltucek So far, so good, not that I experience drifts often. Usually, once every few days. How about you?

**Comment by kareltucek** [comment]
Well, I can induce them intentionally...

**Comment by kareltucek** [comment]
The more pressing issue is whether the algorithm causes any false positives.

**Comment by mondalaci** [comment]
What happens then? Does your algorithm detect drifts and reset the trackpoint?

**Comment by kareltucek** [comment]
Yes.

**Comment by mondalaci** [comment]
Great news! How often do you usually experience drifts without this fix?

**Comment by kareltucek** [comment]
Rarely, unless I try to induce them on purpose.

(Also this fix has no effect on whether or not I experience drifts. Only it will resolve them after a few seconds of such a drift.)

**Comment by mondalaci** [comment]
I expected a more specific answer than "rarely". :)

I asked to figure out how long should we test your fix before merging it. What do you think?

**Comment by kareltucek** [comment]
I don't think we can test this very thoroughly, so we should probably just release it and wait if anyone complains.

**Pull request merged**
