### PR TITLE
Fix up mouse HID report descriptors.

### PR DESCRIPTION
**Pull request by abcminiuser**
I've noticed the key cluster trackball (mouse X/Y scrollwheel) is quite janky on my system, with movements being rather chaotic. I haven't had any luck with fixing that yet today - first I assumed the trackball was actually dual quadrature rather than pulsed axis, then I tried using ISRs to handle the pin changes just in case the MCU was missing them.

While testing, I did find a few oddities in the HID descriptors that should be corrected:

1) Constant padding entries should be marked as CONSTANT only, without DATA or other flags
2) The mouse X/Y wheel reports had some bizarre feature reports listed for configurable resolution multipliers that weren't actually implemented in the firmware
3) The mouse HID descriptors have some PUSH/POP HID entries in them that are both not required, and will have some very "interesting" (read: incorrect) behaviors on some systems.

This PR cleans up the HID report descriptors so we at least advertise to the host reports that we will actually send, or will actually consume.

The `bcdDevice` bump is to force Windows and other hosts to re-fetch the descriptors when the device re-enumerates, rather than using any cached versions.

This PR also changes the reported endpoint size of the system HID interface from 1 byte to the more standard 8 bytes; even if the extra bytes aren't used, it's better to report standard endpoint sizes for broader compatibility.

### CODE REVIEW

**Comment by mondalaci** [comment]
@abcminiuser Thanks so much for these fixes! We would have never noticed the USB-related issues. Do you think it was the cause of #314?

**Comment by abcminiuser** [comment]
Hard to say, but I suspect that's more of an issue on the Linux end. The descriptors for the device were advertising reports that the device wouldn't accept, which could cause all sorts of issues, as well as using push/pops which are frequently implemented poorly.

More likely the device lacking support for boot protocol support is what's broken support with some KVMs and BIOS, and the lack of support for the mandatory HID interface requests like SetIdle and GetReport will break various hosts.

The best place to start would be to download and run the keyboard firmware (as it is now) against [the USB-IF compliance test tool](https://www.usb.org/document-library/usb20cv-x64-bit) to see how many tests we fail. I've been trying to do that to see what needs to be fixed, but lack a Windows host with the required EHCI controller at the moment. If you *do* have suitable hardware, try running the full Chapter 9 tests along with the HID tests and send me the generated report - that will greatly help.

Getting 100% compliance with the tool doesn't guarantee no compatibility issues, but it at least gives us a fighting chance to work against most hosts.

**Comment by mondalaci** [comment]
@abcminiuser You piqued my interest regarding the USB compatibility tool, which I was unaware of. I think my ThinkPad T520 has the required EHCI controller, and I've installed the tool, but I get the following upon pressing the Run button:

usb

Looks like a permission issue. When right-clicking on the icon of the tool, the "Run as Administrator" option is unavailable. I'm not exactly a Windows guru. Any ideas?

**Comment by abcminiuser** [comment]
Hrm, your user directory shouldn't be protected against apps run with your user account - more likely it's the (lack of) UTF-8 awareness in that tool that's breaking it (note the wonky characters in the path). The tool is fairly...errr...engineering quality, so I wouldn't be surprised. It might be worth making a new account with a latin name and see if that fixes it.

There's a newer 3.0 compliance tool that will run on newer xHCI USB host controllers, but I suspect it'll have the same issues even  if you have compatible hardware. It's been a frustrating week for me; of all the systems in my house, they either have a single USB controller (and I don't have any PS2 mice to control the app while the tester takes over the controller), have hardware failures since I last tried to boot them, or both.

I've ordered a cheap USB3 PCI Express card from eBay, so I should (finally) be able to run the tests myself later this week.

At a minimum you're going to fail the HID specific tests due to missing mandatory HID class requests. I've started work on those in https://github.com/abcminiuser/uhk-firmware/tree/feature/hid_class_requests but need to understand the timer system in the codebase before I can implement the SetIdle request. Once those are fixed, there's still legacy boot protocol to consider, as well as fixing any other failures the compliance tool points out.

**Comment by mondalaci** [comment]
Thank you! Then I'm abandoning my attempts at the USB compliance too, and waiting for you. Excited about your findings!

**Pull request merged**
