### PR TITLE
Add ToggleLayer usb command.

### LINKED ISSUE #324: Expose layer toggling via USB
Hi! I was wondering if it would be possible to use a MIDI foot-controller to activate and deactivate layers in the UHK.

I can write the C++ application that listens to MIDI myself, but I don't know if one can send commands to the UHK in real time and do so fast enough.

Might this be possible?

### PR DESCRIPTION
**Pull request by kareltucek**
Closes #324

### CODE REVIEW

**Comment by mondalaci** [comment]
Would it be possible rather to invoke a macro command via USB to implement this? It's quite a niche use case, and introducing a dedicated USB command doesn't seem justified.

**Comment by kareltucek** [comment]
Macro engine has a separate layer switching mechanism, therefore I think a usb command that connects to the core implementation is justified, at least at the moment.

**Comment by mondalaci** [comment]
What's the practical difference between the two?

**Comment by kareltucek** [comment]
As far as I remember, layer locked from macro can only be unlocked from a macro.

Admittedly, another solution is to rework the layer switching mechanism..

**Comment by kareltucek** [comment]
But I guess I can do that, and it should eventually be done anyways...

**Comment by mondalaci** [comment]
Sounds great! I'd much prefer the latter solution.

**Comment by kareltucek** [comment]
Ok!

**Pull request closed without merging**
