### PR TITLE
Improve debug output.

### PR DESCRIPTION
**Pull request by kareltucek**
Just new development-related functionality. Nothing to test here.

### CODE REVIEW

**Comment by mondalaci** [comment]
Please resolve the conflict.

**Comment by kareltucek** [comment]
Conflict? I see no conflict. Even a dummy branch merges just fine.

**Comment by mondalaci** [comment]
There's indeed no conflict. I'm not sure what I saw, but the build errors out:

```
    CC    key_vector.c
    CC    slave_protocol.c
    AS    startup_MK22F51212.S
    LD    uhk60v2.axf

/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: build_make//home/laci/projects/firmware/lib/KSDK_2.0_MK22FN512xxx12/devices/MK22F51212/gcc/startup_MK22F51212.o: in function `Reset_Handler':
(.text+0x60): undefined reference to `data2_at'
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: (.text+0x64): undefined reference to `data2_start'
/usr/lib/gcc/arm-none-eabi/10.3.1/../../../arm-none-eabi/bin/ld: (.text+0x68): undefined reference to `data2_end'
Memory region         Used Size  Region Size  %age Used
    m_interrupts:          1 KB         1 KB    100.00%
          m_text:      112484 B       463 KB     23.73%
          m_data:       54104 B        64 KB     82.56%
        m_data_2:       58720 B      65280 B     89.95%
        m_noinit:          16 B        255 B      6.27%
collect2: error: ld returned 1 exit status
make: *** [../../scripts/Makedefs.mk:203: build_make/uhk60v2.axf] Error 1
```

**Comment by kareltucek** [comment]
This is because the submodule is checked out on incompatible commit... 

I will merge master in there, that should fix it. 

(The other way is clearly to check out correct commit in the submodule.)

**Comment by kareltucek** [comment]
(should be fine now)

**Pull request merged**
