### PR TITLE
Secondary roles.

### LINKED ISSUE #207: Secondary role issue
- Firmware: 8.5.4
- Agent: 1.2.12
- OS: Windows 10

To replicate this issue, assign the "Mod" layer as a secondary role to the right spacebar, using Space as scancode (default). This enables the use of the arrow cluster with one hand, while still being able to use the right spacebar as Space when tapping.

Issue: Whenever space and another key are quickly pressed alternately, most spaces are not registered (e.g., alternating "a" and space: _aa a a aa a a aaaaaa_). Issue can be also replicated when typing very fast since some spaces are not registered between words. This issue is solved when the secondary role is deactivated (e.g. _a a a a a a a a a_).

Additionally, when enabling the secondary role through a third party software (TouchCursor: https://martin-stone.github.io/touchcursor/) and disabling the secondary role in the UHK, the issue disappears. This suggests that the issue is firmware related.

### PR DESCRIPTION
**Pull request by kareltucek**
Resolves #207.

Here is some code - mainly for testing purposes and for discussion at this point. 

I have extended the postponer by time management and implemented djrenren's proposal. At this point it is not working very well. I will probably implement my original strategy later.

### CODE REVIEW

**Comment by mondalaci** [comment]
@kareltucek Do you plan to pursue this any further? I don't like to keep PRs hanging for long.

**Comment by kareltucek** [comment]
> @kareltucek Do you plan to pursue this any further?

Yes. I do already have written the more advanced version, but need to find time to test it and hunt down any problems...

>  I don't like to keep PRs hanging for long.

Feel free to close it for the moment so that it does not bug you :-).

**Comment by mondalaci** [comment]
Thanks for the quick follow-up! No worries, I'm not bothered by it so much. :) Feel free to make further commits, and I'll merge this PR when the time comes.

**Comment by kareltucek** [comment]
This should be now prepared. To test the advanced strategy, you will need to set the strategy in code, and then to go through parameters (there are actually multiple ways of parametrizing, each fitting different sort of writers...).

**Comment by mondalaci** [comment]
Thanks for your PR! It looks highly configurable, and I'm getting totally lost. :)

Can you make some firmware builds with different configuration values, and post them to #207 for everyone to test?

Does your PR perhaps address [this issue](https://github.com/UltimateHackingKeyboard/agent/issues/792), too?

**Comment by kareltucek** [comment]
> Thanks for your PR! It looks highly configurable, and I'm getting totally lost. 

Well, part of the features are implemented based on the djrenren's elaboration. I don't have any idea how exactly are other people used to incorporate those features into their setups, therefore I can only provide my preferred setup and djrenren's.

Will do that tomorrow, and will throw in some documentation, since I guess it will be much more useful than just the two random configurations...

> Does your PR perhaps address [this issue](https://github.com/UltimateHackingKeyboard/agent/issues/792), too?

Well, yes and no. The alphanumeric-friendly strategy contains the timeout just as requested in 792, but it still remains the alphanumeric-friendly strategy. It cannot be configured to act as the simple resolution strategy.

Yet the simple strategy has some strong benefits over the alphanumeric-friendly one due to which (IMHO) should not be considered deprecated. As a result I would consider that a separate feature request.

**Comment by mondalaci** [comment]
@kareltucek Is this PR still relevant, or should it be closed?

**Comment by kareltucek** [comment]
Still relevant.

**Comment by ration** [comment]
Is there any progress on this? I tried this PR version and the timing options appear to make the secondary role timing configurations much much more usable.

**Comment by mondalaci** [comment]
@kareltucek This PR is one and a half years old, and I'd like to close or merge it. Please suggest how to proceed.

**Comment by kareltucek** [comment]
Lets close it then

**Comment by ration** [comment]
Is this functionality anywhere else? Namely fine tuning the secondary role timeout?

**Comment by kareltucek** [comment]
There are the ifPrimaty ifSecondary macros which do provide more alphanumeric friendly resolution than the native strategy, but indeed they cannot be custized as much as this old PR.

**Pull request closed without merging**
