### PR TITLE
Build linux in CI

### PR DESCRIPTION
**Pull request by stephengroat**
Haven't gotten the perfect `gcc-arm-embedded` package from nix and the travis file is a little bit messy, but it includes a ~3 minute linux build on travis using `nix` as a package manager

### CODE REVIEW

**Comment by mondalaci** [comment]
Am I right that now the Linux build succeeded and OSX failed? Do we need two builds? If not, which one would you prefer and why?

**Comment by stephengroat** [comment]
slight issue with the `linux` build: the version of `gcc-arm-embedded` (the toolchain) doesn't exactly match what you guys are using. let me see if i can get both working, the only problem i'm currently having is some whitespace issues that should be solve-able

**Comment by stephengroat** [comment]
fixed, you now get both `osx` and `linux`

i need to work on how to use `nix` to get the proper version of `gcc-arm-embedded` toolchain installed, but this is ready to merge

**Comment by mondalaci** [comment]
Thanks, you're seriously awesome!

What's the advantage of building for two OSes? I'd think that it can break easier (in case either build breaks) which is not an advantage, although if either breaks I can just comment it out temporarily and the other will keep working.

**Comment by stephengroat** [comment]
Sorry, i thought the comment sent (i'm currently suffering from some sketchy internet).

the `linux` build currently has the wrong version of the `gcc-arm-embedded` toolchain. I haven't figure out `nix` well enough to get the right version yet.

in short: `linux` is fast but has the wrong `gcc-arm-embedded` toolchain version, `osx` is correct but super slow

**Comment by mondalaci** [comment]
Makes perfect sense, thank you for explaining! Let me merge this one, and then you can send another one if you'll have time to figure out Linux even better.

Thanks so much!

**Pull request merged**
