### PR TITLE
Postponed time fix

### PR DESCRIPTION
**Pull request by kareltucek**
Reported in https://forum.ultimatehackingkeyboard.com/t/ifsecondary-config-to-match-deprecated-resolvesecondary/395/6 

Fixes the problem, and adds a debugging feature for similar scenarios.

Changelog line could be for instance: Fix behavior of the advanced secondary role strategy when rolling over multiple secondary role keys. Latter keys tended to produce false secondary role.

### CODE REVIEW

**Comment by kareltucek** [comment]
[uhk-firmware-10.1.0-postponed_time_fix.tar.gz](https://github.com/UltimateHackingKeyboard/firmware/files/12384087/uhk-firmware-10.1.0-postponed_time_fix.tar.gz)

**Comment by mondalaci** [comment]
Are you sure that the introduction of `statsRecordKeyTiming` is fully justified?

There is a value to an easy-to-comprehend, small API surface, so we should think twice when adding new commands.

**Comment by kareltucek** [comment]
Well, either that, or having to write that again from scratch next time when I need to debug timing issues.

**Comment by mondalaci** [comment]
I think it'd be worth removing `statsRecordKeyTiming` for now and permanently adding it back if it's useful long-term.

**Comment by kareltucek** [comment]
Given you are concerned about API surface, what about just removing it from the documentation then?

**Comment by mondalaci** [comment]
It'd make practical sense, but I'm also a big fan of transparency when it comes to the documentation as a whole. Are there any other development-related commands? Maybe you could extract them into a separate document.

**Comment by kareltucek** [comment]
Basically the entire `stats*` "namespace".

**Comment by kareltucek** [comment]
Or maybe just creating a new section in the grammar? The rest of the document is meant to be searched anyways.

**Comment by mondalaci** [comment]
You mean moving the grammar to a dedicated page?

**Comment by kareltucek** [comment]
No, I mean as there are 
```
############
#DEPRECATED#
############
```
and REMOVED sections, we could add a 
```
######################
#DEVELOPMENT COMMANDS#
######################
```
section

**Comment by mondalaci** [comment]
Please do so.

**Comment by kareltucek** [comment]
Done.

**Pull request merged**
