### PR TITLE
Add minimalistic debug library.

### PR DESCRIPTION
**Pull request by kareltucek**
This is just an offer of my private debugging mini library. 

It is quite handy when one needs to watch just a couple of variables. 

Usage:
- Define/uncomment `WATCHES` directive.
- Place some watches (i.e., macro calls) into the code, while specifying unique slot in range 0-6 as second parameter.
- While using the keyboard, tap one of the left half top row keys. 
- Led display will start watching that value every 500ms (i.e., first call of the macro after 500ms since last call is shown onto display and will remain for at least the next 500ms)

### CODE REVIEW

**Comment by mondalaci** [comment]
Your debug library seems quite handy! I'll merge it, but let me make a couple of suggestions first.

- `ShowNumberExp` might be a better name than `ShowNumberMag`. I'm not sure if it's worth exposing it because it can be used via other relevant functions. It would be more intuitive for me if the alphabetic exponent part were placed at the end, not at the beginning.
- The exponent notation shouldn't be used for numbers below 1,000.
- I think it's overkill to create a dedicated directory for these files for the time being. Let's use `right/src/debug.[ch]` for now.
- Please follow our coding standards.

**Comment by kareltucek** [comment]
All good points, will refactor it.

**Comment by kareltucek** [comment]
Resolved. 

Is the codestyle fine like this? (I am quite blind in this respect 😅.)

**Comment by mondalaci** [comment]
Well done, and thank you! :)

**Pull request merged**
