### PR TITLE
Fade uhk80 leds gradually.

### LINKED ISSUE #1001: Gradual LED fadeout
Instead of suddenly disabling the key backlight and LED display upon timeout, make them gradually fade out over a second.

The global brightness control feature of the LED drivers and OLED display should be used instead of individual LED control. If they can't be used, let me know so we can discuss the implementation.

### PR DESCRIPTION
**Pull request by kareltucek**
Closes #1001

### CODE REVIEW

**Comment by mondalaci** [comment]
Very smooth.

Should we create a separate issue for fading modules? (Which would be blocked by the UHK 80 module firmware update issue.)

**Comment by kareltucek** [comment]
Yes please.

Since leds are controlled over i2c from master. I actually dont think tht module update will be needed

**Comment by mondalaci** [comment]
You're right about I2C.

Also, should I create a fade issue specifically for the UHK 60 as it's not supported by this PR?

**Comment by kareltucek** [comment]
No. uhk60 and modules share the same code I believe.

**Pull request merged**
