### PR TITLE
Light entire matrix at the beginning of switch test mode.

### LINKED ISSUE #1058: All LEDs must be lit in switch testing mode
```
erase-hardware-config.ts
factory-update-uhk60.ts firmwareDir uhk60v2
write-hardware-config.ts uhk60v2 ansi
set-variable.ts testSwitches 1
```

After executing the above but before pressing any key, the ANSI LShift LED should be enabled, but it's not on the UHK 60.

image

### PR DESCRIPTION
**Pull request by kareltucek**
Closes #1058

### CODE REVIEW

**Comment by mondalaci** [comment]
The issue persists. Have you tested it?

**Comment by kareltucek** [comment]
That last commit fixes only one minor issue that I have found while testing. As for the cause of the invalid key count, I am still in the dark.

**Comment by mondalaci** [comment]
Ok, thanks! As soon as this gets fixed, I'll release a new firmware.

**Comment by kareltucek** [comment]
Long story short, try now.

**Comment by mondalaci** [comment]
On my ANSI UHK 60 v2, in switch test mode, when I press the left Shift, the left ISO Shift LED lights up instead of the ANSI LED.

**Comment by kareltucek** [comment]
I can't reproduce it. Have you powercycled the board after writing that hardware config? Hardware config is still reloaded only after power cycling.

**Comment by mondalaci** [comment]
This PR works when power-cycling my UHK after `write-hardware-config.ts uhk60v2 ansi` but before `set-variable.ts testSwitches 1`

Can you reload the hardware config with reasonable effort after writing it? Alternatively, we can provide an ansi/iso parameter to testSwitches, but that would be redundant. The bottom line is that I prefer to make factory flashing fast and avoid unnecessary steps, such as a firmware reboot.

**Comment by kareltucek** [comment]
Well, this reloads the led settings when the config is written. I have not tried to update the other settings, such as the serial number though.

**Pull request merged**
