### PR TITLE
Implement named variables.

### LINKED ISSUE #614: Support of register values in setLedTxt
Hello, this is not an urgent matter but it would be nice:

I am currently creating a basic VIM engine inside the keyboard and I want to display a number from the registry inside the led text panel.

currently `setLedTxt 2000 #22` displays "22" in the led display

### LINKED ISSUE #620: Ability to 'adjust' config values
As discussed in https://github.com/UltimateHackingKeyboard/firmware/issues/437

### LINKED ISSUE #630: [Feature proposal] Named variables
I plan to do the following refactor of the language related to tokenization, variables and config values: 

- Introduce implicitly-typed named variables. This would work by having string references pointing into configuration buffer. I.e., 3-byte string reference (2-byte config buffer offset, 1-byte length), another 1 byte for variable type.  These would be allocated when first used and kept in a statically-allocated sored array, accessed via binary-search.
  - assume support for: int, float, bool
  - however, options for future extension are nearly endless...
- Change '#<reg index>' syntax to '$<variable name>'
- Change `setReg <reg number> <value>` to `setVar <variable name> <value>`.
- Introduce numeric expressions as `$(EXPRESSION)`.
- Implement proper string tokenization with bash-like variable interpolation. E.g., `write "String that interpolates $thisVariable.\n"` or `'Produce literal $ character.'`.
- Merge config value and variable namespaces for reading. E.g., allow substituting `write "$module.trackball.baseSpeed"`.
- However, leave separate `set <config value>` and `setVar <variable name>` commands for writing, in order to preserve errors when a typo is made when trying to set a config value.
- Refactor some namespaces:
  - Change `%<index>` syntax to `$queuedKeypress.<index>`
  - Introduce `$keyId.<keyId abbreviation>` and `$scancode.<KEYABBREV>` namespaces. However, allow omitting `$<namespace>.` prefix in commands that expect a specific type. E.g., allow `ifGesture a` instead of `ifGesture $keyId.a` or `tapKey a` instead of `tapKey $scancode.a`
  - Reference number keys in keyId namespace by words ("one", "two", ...) in order to preserve old KEYID syntax. (I strongly believe that unambiguous numeric references have their merits. Also, changing meaning of an existing syntax to something entirelly different while not discarding old syntax validity is just rude.) 

Memory requirements:
- Current 32\*4 byte array for registers will be replaced by a 32\*8 array, i.e., additional 128 bytes of RAM will be consumed.

Your chance (everyone) to protest or share any thoughts is now.

### PR DESCRIPTION
**Pull request by kareltucek**
Changes:
- Introduced named, dynamically typed variables. I.e., `setVar` command and `$` syntax. E.g.:
   ```
  setVar myDelay 50
  set doubletapDelay $myDelay
  ```
- Introduced expression parser that allows in-line arithmetics (`+`, `-`, `*`, `/`, `%`, `min(...)`, `max(...)`) and boolean conditions (`<`, `<=`, `>`, `>=`, `==`, `!=`, `!`, `&&`, `||`). E.g.:
  ```
  ifShift set leds.brightness ($leds.brightness * 1.5 + 0.01)
  ifNotShift set leds.brightness ($leds.brightness / 1.5)
  ```
- Introduced `if (EXPRESSION)` command. E.g.:
  ```
  if ($a < 2 || $a > 4) tapKey a
  ```
- Introduced string parser. Strings should from now on be enclosed in double or single quotes. Double-quote strings support variable expansion and `\` escapes. E.g.:
  ```
  write "Current keystrokeDelay is $keystrokeDelay. One plus one is $(1 + 1).\n"
  write 'This is literal "$" character. And here you have an apostrophe '"'"'.'
  ```
- Introduced keyid parser. As a result, ifGesture, ifShortcut and some other commands now accept keyid abbreviations. E.g.:
  ```
  ifShortcut a b holdLayer fn
  ```
- Introduced `validateUserConfig` command, mainly for development purposes.
- `setLedTxt` now accepts numeric expressions. E.g.:
  ```
  setLedTxt 500 $keystrokeDelay
  ```
- Configuration values now can be retrieved using `$<name>` syntax just as variables. E.g.:
  ```
  set leds.brightness ($leds.brightness * 1.5 + 0.01)
  ```
- Deprecated `#`,`%` and `@` syntaxies.
- Deprecated registers. I.e., `ifRegEq`, `ifNotRegEq`, `ifRegGt`, `ifRegLt`, `setReg`, `addReg`, `subReg`, `mulReg` commands
- Deprecated `writeExpr` and `setStatusPart` commands.
- Refactored most of the macro codebase to a new token-parsing scheme (parser context and `consume*` operators. This has probably introduced some new bugs. Please, let us know on github or on our forum if you encounter any.

Closes #614, closes #620, closes #630.

Sorry for the PR length 😅. Originally it was split into multiple commits, until I realized that I had forgotten to commit new files... ...which has led me to squash the branch to prevent inconsistent states on the branch.

### CODE REVIEW

**Comment by mondalaci** [comment]
Please bear with me until I review your (very impressive) PRs; I want to release the current firmware master with proper implementation of the md5sum feature and a related Agent version first so that the chance of users bricking their UHKs would decrease dramatically.

**Comment by likern** [comment]
That looks very interesting. What it lacks  - high quality documentation and tutorials.
The power of macros are much more powerful then what I can get from documentation.

**Comment by mondalaci** [comment]
@likern Agreed, and I think #647 will resolve the mentioned issues.

**Comment by mondalaci** [comment]
@kareltucek Would you please write example commands for the points mentioned?

I'm asking because I find this PR quite overwhelming, and examples I can easily test would help a lot.

Going forward, please try to submit smaller PRs. That way, I can review them much faster without getting my brain melted :)

**Comment by kareltucek** [comment]
> Would you please write example commands for the points mentioned?

Edited the leading post.

**Comment by mhantsch** [comment]
This is impressive; I like the new syntax.

My biggest question is: how is compatibility with existing macros kept? Or simply not, and users would have to rewrite all their macros once they install this firmware?

**Comment by kareltucek** [comment]
In this PR, most old syntax is preserved but throws deprecation warnings accompanied by migration instructions. But yes, users are expected to rewrite their macros. I expect to remove the deprecated syntaxes in the next major release.

**Comment by mondalaci** [comment]
The macro engine accepts `setVar asdfasdfasdfasdfasdfasdfasdf 50`, even though, I assume, the variable name is too long. I guess the engine discards the end of the name from the nth character. If so, it'd make sense to prohibit overly long names.

**Comment by kareltucek** [comment]
Good point, fixed, although the name is not too long, by far. Actually, asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasd is still valid length.

**Comment by mondalaci** [comment]
I suggest changing `Variable not found! myDelay` to `Variable not found: myDelay`

`if ($a < 2 || $a > 4) tapKey a` throws:

```
Error at $onInit 1/9: Failed to parse expression, closing parenthess expected.
> 9 | if ($a < 2 || $a > 4) tapKey a
>   |                  ^
Error at $onInit 1/9: Unrecognized command: >
> 9 | if ($a < 2 || $a > 4) tapKey a
>   |                  ^
```

**Comment by mondalaci** [comment]
`write 'This is literal "$" character. And here you have an apostrophe '"'"'.'` throws:

```
Error at $onInit 1/9: Dispatch data got stuck! Please report this. his
> 9 | write 'This is literal "$" character. And here you have an apostrophe '"'"'.'
>   |         ^
```

**Comment by mondalaci** [comment]
`setLedTxt $keystrokeDelay` empties the text portion of the LED display.

**Comment by mondalaci** [comment]
Am I correct that this is a slightly breaking change because single-digit keyIds don't work as they used to?

**Comment by kareltucek** [comment]
> Am I correct that this is a slightly breaking change because single-digit keyIds don't work as they used to?

Yes.

**Comment by mondalaci** [comment]
Then, after merging this PR, I'll bump the major smart macro version and, as a result, the major firmware version.

I'm unsure whether I should bump the major smart macro and firmware version again after you eventually remove the added deprecation warnings, but I think I shouldn't.

**Comment by kareltucek** [comment]
Well, there were similar minor violations of compatibility in the past upon which you did not raise the major number. For instance, switching leds.fadeTimeout from minutes to seconds. Given this, I don't think that you are strictly obliged to bump the major number just because of that relatively minor change in the keyid semantics. 

I think it makes sense to bump the major versions just once for a feature, no matter whether you do it now, or upon removal of the deprecated stuff.

In any case, other things should be done before the next major release, so please don't release major version straight after merging.

**Comment by mondalaci** [comment]
Great points! What do you want to do before bumping the major version?

**Comment by kareltucek** [comment]
- Resolve #682.
- Add limits to config variables. (That is blocked by this PR.)
- I also wanted to implement #680, but it is troublesome for multiple reasons, so I will probably leave that for another time.

**Comment by kareltucek** [comment]
> `setLedTxt $keystrokeDelay`

This is actually missing time, e.g. `setLedTxt 500 $keystrokeDelay`, sorry about that.

Added error when this happens.

---

Other two bugs are fixed.

**Comment by mondalaci** [comment]
This PR seems complete. Do you still have anything to fix? I assume you'll fix https://github.com/UltimateHackingKeyboard/firmware/pull/674#issuecomment-1712842661 in separate PRs.

**Comment by kareltucek** [comment]
This is complete unless you can find other problems. I will fix the other things in separate PRs.

**Comment by mondalaci** [comment]
Please resolve the conflict, and I'll merge it.

**Comment by kareltucek** [comment]
Done.

**Pull request merged**
