### PR TITLE
Turn LEDs, backlight and display off when sleeping

### LINKED ISSUE #83: Disable LED display during sleep
To save power.

### PR DESCRIPTION
**Pull request by Lauszus**
Fixes #83

### CODE REVIEW

**Comment by mondalaci** [comment]
This works fine when suspending a machine and then waking it up, but has some issues. When I reboot a machine and boot up an OS, backlighting gets permamently disabled until I replug USB. This PR also makes the mouse pointer move very slowly.

**Comment by Lauszus** [comment]
Okay, I will look into it. This PR does not affect the mouse interface, so I can't see how it should affect it?

**Comment by mondalaci** [comment]
By the looks of it the code should not affect mouse speed, but according to my testing it clearly does. Give it a try on Linux. Mouse speed is very sensitive to code changes. Maybe it could be implemented in a more robust manner.

**Comment by Lauszus** [comment]
The following PR needs to be merged for this to work: https://github.com/UltimateHackingKeyboard/KSDK_2.0_MK22FN512xxx12/pull/1.

https://github.com/UltimateHackingKeyboard/firmware/pull/96 also needs to be merged, as I use that to test if a button is pressed.

**Comment by Lauszus** [comment]
Regarding mouse speed, then yes I believe that the real issue if the mouse implementation, as it should not be that sensitive to code changes.

**Comment by Lauszus** [comment]
I assume the mouse speed also depends on the optimization setting then?

**Comment by mondalaci** [comment]
I don't know but chances are good it does.

**Comment by Lauszus** [comment]
Hmm it seems like the layer keys are not always restored correctly when the LEDs are turned back on.

**Comment by mondalaci** [comment]
I can merge #96 but only if you can fix the mouse speed issue soon (about within a week), because that will break the mouse feature usability-wise.

**Comment by Lauszus** [comment]
Just create a dev branch and I will change the base of these PR's.

**Comment by mondalaci** [comment]
`dev` branch pushed.

**Comment by Lauszus** [comment]
Great, I have now changed the base for both of them :)

**Comment by mondalaci** [comment]
Cool, thanks! Please resolve the conflicts so that I can merge this one, too.

**Comment by Lauszus** [comment]
Will do that now. The problem is that you are not actually merging my commit, but are rebasing them. Just tell me to rebase them into one commit if you prefer that.

**Comment by mondalaci** [comment]
I just usually use the "squash and merge" feature of GitHub to merge PRs. Should I use something else?

**Comment by Lauszus** [comment]
I usually just use the default "Create a merge commit", so the history is preserved and you do not rewrite the commits.

**Comment by mondalaci** [comment]
Thanks! Did as you suggested.

**Comment by Lauszus** [comment]
Wait, I did not push the fix for https://github.com/UltimateHackingKeyboard/firmware/pull/97#issuecomment-372091423, but I will just open a new PR :)

**Pull request merged**
