### PR TITLE
add linux builds

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by mondalaci** [comment]
@stephengroat I can see that now Eclipse is installed from a tarball but this build still seems to target OSX. How is it a Linux build? Why is it a step forward compared to the current version?

Thank you!

**Comment by stephengroat** [comment]
@mondalaci it's building two jobs now, one `osx` and one [`precise`](https://travis-ci.org/UltimateHackingKeyboard/firmware/jobs/230896520#L9)

**Comment by mondalaci** [comment]
@stephengroat Where can I see the Linux target in the file? Why not build the whole thing only on Linux?

**Comment by stephengroat** [comment]
@mondalaci i can add in `os: linux` at the top, but it's just the default.

**Comment by mondalaci** [comment]
@stephengroat I see. I think I was confused by `matrix.include.os = osx`. Does it tell Travis to build it also on OSX, not just on Linux? If so, why is this used?

**Comment by stephengroat** [comment]
i don't know if you can see, but the versions of `gcc` that i'm using are currently causing the compilation issues on `linux`.

could you paste a `gcc --version` for me?

**Comment by mondalaci** [comment]
Sure thing!

```
laci@spark ~ $ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by stephengroat** [comment]
sorry, i was referring to the `arm-none-eabi-gcc --version`

**Comment by mondalaci** [comment]
Ah, sure! Sorry, my bad.

```
laci@spark ~ $ arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

But actually, there's another version installed by KDS. I believe this is the one actually used.

```
laci@spark /opt/Freescale/KDS_v3/toolchain/bin $ ./arm-none-eabi-gcc --version
arm-none-eabi-gcc (GNU Tools for ARM Embedded Processors) 4.8.4 20140725 (release) [ARM/embedded-4_8-branch revision 213147]
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by stephengroat** [comment]
ah. i can't actually get the a toolchain that old from the [arm toolchain site](https://developer.arm.com/open-source/gnu-toolchain/gnu-rm)

**Comment by mondalaci** [comment]
I'm sorry to hear about it. I'm surprised that newer versions of gcc don't build the firmware. Alternatively, maybe gcc could be installed from a PPA such as [this](https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa). In any case, thank you for your work!

**Comment by stephengroat** [comment]
you can see the errors here (https://travis-ci.org/UltimateHackingKeyboard/firmware/jobs/230896520) that i get with a newer arm toolchain

**Comment by mondalaci** [comment]
Thanks for the link! Unfortunately, I have no idea how to resolve this error:

```
/home/travis/build/UltimateHackingKeyboard/firmware/gcc-arm-none-eabi-6-2017-q1-update/bin/../lib/gcc/arm-none-eabi/6.3.1/../../../../arm-none-eabi/bin/ld: section m_usb_bdt VMA [000000001fffa400,000000001fffa5ff] overlaps section .bss VMA [000000001fff2000,000000001fffac03]
```

**Pull request closed without merging**
