### PR TITLE
Implement config manager.

### PR DESCRIPTION
**Pull request by kareltucek**
Moves all configuration to one central place, and thus allows global reset.

This does not reset component states.

### CODE REVIEW

**Comment by mondalaci** [comment]
How should I test this?

What do you mean by "component states"?

**Comment by kareltucek** [comment]
I mean macro engine state (scheduler state, macro states, possible static variables), mouse key state arrays, and other similar things.

**Comment by mondalaci** [comment]
How should I test this PR? I'm unsure.

**Comment by kareltucek** [comment]
Choose a settings that is not a part of the userconfig and does not edit keymap/ledmap in ram. Then write it from a macro (not a macro event). Now save configuration from Agent and test that the setting was resetted.

**Comment by mondalaci** [comment]
Please provide me with a couple of such example settings.

**Comment by kareltucek** [comment]
I am not at computer right now. I guess autoRepeatDelay, autoShiftDelay, chordingDelay, secondaryRole.advanced.triggerByPress, stickyModifiers, modifierLayerTrigger, oneShotTimeout may be of that kind, but please check that against Agent.

**Comment by mondalaci** [comment]
My trackpoint speed settings are disrespected regardless of the module section settings.

**Comment by kareltucek** [comment]
> My trackpoint speed settings are disrespected regardless of the module section settings.

Ouch.

Fixed.

**Pull request merged**
