### PR TITLE
Implement touchpad hold continuation timeout.

### PR DESCRIPTION
**Pull request by kareltucek**
As discussed in https://forum.ultimatehackingkeyboard.com/t/touchpad-double-click-to-drag-continuation/595/4

`set module.touchpad.holdContinuationTimeout 200`

Should it be enabled by default?

### CODE REVIEW

**Comment by mondalaci** [comment]
Works great! I'm not sure whether to enable it by default. How do most touchpads work out of the box in this respect? We should meet most users' expectations.

In any case, this setting will be exposed in the dedicated touchpad module configuration page of Agent.

**Comment by kareltucek** [comment]
> How do most touchpads work out of the box in this respect?

No idea. None of the laptops I work with has tap detection at all. (I.e., left click has to be done by a dedicated button.)

**Comment by mondalaci** [comment]
Just merged the PR as it is, as I believe having this option disabled by default is sensible. This option will be exposed via Agent, so it'll be easy to explore.

**Comment by mhantsch** [comment]
> I'm not sure whether to enable it by default. How do most touchpads work out of the box in this respect?

Some of those I know just slowly keep moving the pointer when you reach the end of the touchpad and hold your finger there. I think they call the feature "edge scrolling".

**Pull request merged**
