### PR TITLE
Added Makefiles for compiling the two projects

### PR DESCRIPTION
**Pull request by Lauszus**
Needs some testing before merging

### CODE REVIEW

**Comment by Lauszus** [comment]
I also have some code for flashing the firmware using JLink, but I have not added it yet since I have not tested it yet.

**Comment by eltang** [comment]
GPLv2 only and GPLv3 are incompatible, so wouldn't this create a license conflict?

**Comment by Lauszus** [comment]
@eltang fixed in https://github.com/UltimateHackingKeyboard/firmware/pull/110/commits/aa4105bdc3919a9afe6f7f2e4e637a2db60af99e.

**Comment by Lauszus** [comment]
I added support for flashing the two half using JLink flash in 66252ea. Can someone with a JLink debugger test it?

Just run:

```bash
make flash-jlink
```

**Comment by mondalaci** [comment]
I got the following error on Linux Mint:

```
laci@spark ~/projects/firmware/right $ make
    CC    key_states.c
In file included from /home/laci/projects/firmware/right/src/key_states.h:6:0,
                 from /home/laci/projects/firmware/right/src/key_states.c:1:
../lib/KSDK_2.0_MK22FN512xxx12/devices/MK22F51212/drivers/fsl_common.h:34:20: fatal error: assert.h: No such file or directory
 #include <assert.h>
                    ^
compilation terminated.
../scripts/Makedefs.mk:202: recipe for target 'build_make//home/laci/projects/firmware/right/src/key_states.o' failed
make: *** [build_make//home/laci/projects/firmware/right/src/key_states.o] Error 1
```

**Comment by Lauszus** [comment]
What version of ARM gcc are you using?

**Comment by mondalaci** [comment]
laci@spark ~/projects/firmware $ arm-none-eabi-gcc --version
arm-none-eabi-gcc (15:4.9.3+svn231177-1) 4.9.3 20150529 (prerelease)
Copyright (C) 2014 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by Lauszus** [comment]
Can you try to update it to something more recent (see .travis.yml)?

**Comment by Lauszus** [comment]
@mondalaci see: https://stackoverflow.com/a/34467175.

**Comment by mondalaci** [comment]
Finally, it builds! I installed the [GNU Arm Embedded Toolchain PPA](https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa) by typing:

```
sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa
sudo apt-get update
sudo apt-get install gcc-arm-embedded
```

**Pull request merged**
