### PR TITLE
Wake from led sleep on non-report actions, refactor activity detection.

### PR DESCRIPTION
**Pull request by kareltucek**
Reported in https://forum.ultimatehackingkeyboard.com/t/setting-led-fade-timeout-back-to-0-doesnt-restore-leds/455

### CODE REVIEW

**Comment by mondalaci** [comment]
I can't reproduce this issue. I `set leds.fadeTimeout 1` then `set leds.fadeTimeout 0`, and the LEDs are permanently enabled. Same via the LED settings.

**Comment by kareltucek** [comment]
So your LEDs don't even turn off after 1 second of inactivity?

**Comment by mondalaci** [comment]
They do, but after setting the value to zero, the LEDs turn on, as expected, unlike for the reporting user. In other words, how should I reproduce this issue?

**Comment by kareltucek** [comment]
You must be doing something more than that. 

- Execute `set leds.fadeTimeout 5`.
- Wait 5 seconds till leds go dark.
- Execute `set leds.fadeTimeout 0`. 
- Don't press any other keys, or touch your modules. Leds should still be dark.

**Pull request merged**
