### PR TITLE
Add resetTrackpoint command.

### LINKED ISSUE #382: Trackpoint module drift
Sometimes, the trackpoint module drifts. In other words, the mouse pointer keeps moving in a direction without any input being applied. This is a known issue of original IBM/Lenovo TrackPoints, too.

Given that the direction and speed of such drifts are constant, I plan to detect drifts on the firmware level, then execute a PS/2 reinitialization sequence. The trackpoint firmware will contain the above fix without affecting anything else.

### PR DESCRIPTION
**Pull request by kareltucek**
Closes #382.

(Reworked according to requests in #502.)

### CODE REVIEW

**Comment by mondalaci** [comment]
Now the trackpoint module is not immediately useable right after attaching it due to the explicit recalibration. Please don't reset it upon firmware startup.

**Comment by kareltucek** [comment]
Oops. Fixed.

**Comment by mondalaci** [comment]
The resetTrackpoint command seemingly doesn't do anything now. I can move the pointer with the trackpoint module uninterruptedly when triggering it.

**Comment by mondalaci** [comment]
I've just realized that this command only works when extended macros are enabled. Please enable it always.

**Comment by kareltucek** [comment]
Good catch! Fixed.

**Pull request merged**
