### PR TITLE
Fix NewPairings flag and add GetNewPairings paging.

### PR DESCRIPTION
**Pull request by kareltucek**
Contains fixes for https://github.com/UltimateHackingKeyboard/firmware/issues/980

Waiting for @ert78gb to test and implement Agent side.

Migrated from https://github.com/UltimateHackingKeyboard/firmware-uhk80/pull/369

### CODE REVIEW

**Comment by ert78gb** [comment]
I am implementing the feature. I paired my UHK80 to my notebook via bluetooth . Everything worked as described in the https://github.com/UltimateHackingKeyboard/firmware/issues/980#issuecomment-2537898236. Why I implemented the feature I saved the user config because I modified the brightness of the backlighting. Also paired and un-paired the dongle because I tested something in the process.
I don't remember the exact order of what I did.
But currently, the device status does not report any new BLE paired device available. I also checked the `0 12 0` USB command and it returns with `0`-s.
I unpaired and paired again my keyboard and computer but the still not see any new BLE paired devices.
I also power cycled the keyboard and uploaded the firmware again and no changes.

How could I "reset" the keyboard state to report new BLE address(es) again?

**Comment by kareltucek** [comment]
@ert78gb I have a fixed a bug that made bond-clearing on reboot not work. Sorry for also rebasing this branch while doing so.

A few notes:
- unknown bonds (those not present in host connnections) are (should be) cleared on every config application. I.e., on reboot and on saving from Agent.
- in this branch, restarting HID advertisement may be failing. In that case, please reset (or powercycle or `kernel reboot cold`) your UHK.

**Comment by ert78gb** [comment]
> Sorry for also rebasing this branch while doing so.

I wanted to ask. I support to keep branches up to date. I am fine with merge and rebase too.

**Comment by kareltucek** [comment]
(I am fan of keeping stuff up to date, but I normally favor merges over rebases unless there is a good reason to rebase.)

**Comment by mondalaci** [comment]
@ert78gb I rely on you regarding when to merge this. Please let me know when you figure it out.

**Comment by ert78gb** [comment]
I am working on it tomorrow.

**Comment by kareltucek** [comment]
This diverge has gotten too far out of hand -> merging. (Reason: regressions and conflicts regarding hardware config load order.)

**Pull request merged**
