### PR TITLE
WIP: Initial deserialization code

### PR DESCRIPTION
**Pull request by algernon**
Depends on #28, for the `key_action_t` changes.

Currently updates `CurrentKeymap` directly, this should change in the future, but to keep things simple, I did not want to make the keymap changeable too. That will be a separate step.

At first, I'd like to run this code by you, to see if the direction is fine, or if there's anything I'd need to change substantially.

To try it, uncomment the `deserialize_Layer` line in `main.c`.

The hardcoded layer serialization is this:

selection_013

The `Esc` key is a longpress one, and the longpress action is to switch to the `Mouse` layer.

### CODE REVIEW

**Comment by mondalaci** [comment]
@algernon What a major step forward! We salute you! :vulcan_salute:

Luckily, [we will be able to remove](https://github.com/UltimateHackingKeyboard/agent/issues/136#issuecomment-270952221) `findIndex` in the near future but it's very much necessary in the meantime.

It'd be nice to decompose the code of the various serialization items into different files eventually. I'm thinking about a new `config_parser` directory under `right/src`. The directory hierarchy could resemble https://github.com/UltimateHackingKeyboard/agent/tree/master/src/config-serializer/config-items - What's your take on this?

How should we proceed further? Should Jozsef make Agent export the current keymap, for example?

Thank you so much!

**Comment by algernon** [comment]
I'd keep it in a single file, for a number of reasons:

- It's simpler that way, and the code isn't all that large.
- Having them in one file, most functions `static` allows better compiler optimizations.
- Having a file for the `None` type alone, which is pretty much a one-liner feels like overkill.

For the agent, it makes sense to split them into files, because it has serialization too, into multiple formats, and deserialization likewise. The firmware can only deserialize the binary - a lot less code.

> How should we proceed further? Should Jozsef make Agent export the current keymap, for example?

That would be grand, yes. As an orthogonal step, I'd like to refactor the code so that it does not work with `CurrentKeymap` directly, but the keymap array would have to be passed to the `deserialize_Layer` function. That would lay the foundation for being able to update multiple keymaps, and to deserialize into a temporary place, upon which we could run verification, for example.

**Comment by mondalaci** [comment]
Your reasons make a lot of sense to me. Let's keep the configuration parser in one file them. Later on, it might make sense to put the macro parser to a separate file, though. I'm comfortable having about 200 lines per file but not much more, and chances are the keymap + macro parser would grow way beyond that.

I'm not sure whether we want to use an alternative keymap array besides `CurrentKeymap`. The reason is that a single keymap array occupies about 5K RAM and the configuration can contain loads of keymaps resulting in a shortage of memory, even on our processor. I imagined an alternative approach.

The parser would read the whole configuration and index the offset of every keymap into a ` uint16_t KeymapOffsets[]` array. Then whenever a keymap switch action gets triggered, we'd parse the relevant keymap and extract it to `CurrentKeymap`.

**Comment by mondalaci** [comment]
As for the verification, a configuration validation step is very much planned, indeed. We'll execute it every time before writing the config into the EEPROM. It would be very nice if the parser returned whether its execution was successful, and if not, it would return the offset where it failed and an error code. That way, debugging would be a pleasure.

**Comment by algernon** [comment]
Yeah, the macro parser is worth putting elsewhere, that one is likely going to be big enough.

I like the keymap idea, having them as an array makes a lot of things simpler.

I'll see what I can do about the error reporting!

**Pull request merged**
