### PR TITLE
Turn on all leds in switch test mode.

### LINKED ISSUE #740: Test mode fix
When switching to factory test mode (`${agent}/packages/usb/set-variable.ts testSwitches 1`), make all LEDs, including ANSI and ISO LEDs, light up (white color).

### PR DESCRIPTION
**Pull request by kareltucek**
Closes #740

### CODE REVIEW

**Comment by mondalaci** [comment]
Please resolve the conflicts.

**Comment by kareltucek** [comment]
Done!

**Comment by mondalaci** [comment]
I've noticed that you've made all the LED segments light up, which is a great idea from a testing standpoint, But the Agent icon is still unlit when Agent is not connected. Please also enable the Agent icon.

**Comment by kareltucek** [comment]
Well, the segment display is just a side-effect, and may be updated by the segment display driver...

But as requested, Agent led is no longer updated in test switch mode.

**Pull request merged**
