### PR TITLE
Add delete navigation mode.

### PR DESCRIPTION
**Pull request by kareltucek**
Someone mentioned this on the forum, and it seems a very nice idea to me, so here we go?

### CODE REVIEW

**Comment by mondalaci** [comment]
I think this feature is too niche, and line deletion doesn't work in Visual Studio Code as it's dependent on the shortcuts of the editor, making it potentially problematic.

**Comment by kareltucek** [comment]
This is not a new feature. It is just adding another remappable slot to the navigation mode system ¯\\_(ツ)_/¯. 

As to line deletion, it is that, or leaving the up/down shortcuts empty...

**Comment by mondalaci** [comment]
If another caret mode is justified, a more general name would make better sense to me, like caret2.

But I'm not sure if this feature is justified, to begin with.

**Comment by kareltucek** [comment]
Allright, let's close it then?

**Comment by mondalaci** [comment]
Yes, I prefer to close this one.

As a rule of thumb, I'd only add features to smart macros that clearly provide value to a fair number of users. Otherwise, we're adding complexity that users must absorb, and simplicity is a feature.

Admittedly, the above is not a strict definition, but I think this feature is below the acceptance threshold.

**Pull request closed without merging**
