### PR TITLE
Rename doubletapDelay to doubletapTimeout.

### PR DESCRIPTION
**Pull request by kareltucek**

### CODE REVIEW

**Comment by mondalaci** [comment]
I'd much rather prefer branching based on smart macro version and explicitly disallow deprecated language elements.

**Comment by kareltucek** [comment]
How?

I can't efficiently branch based on semver in the macro engine given that stock and fork use separate semver spaces. (Which cannot be avoided as long as you keep insisting on changes to already released features while also refusing to inherit macro versioning of the fork.)

I would also much rather not break people's setups when there is no reason to do so.

**Comment by mondalaci** [comment]
Then please comment out the old naming for the official UHK firmware build.

**Comment by kareltucek** [comment]
Like this?

**Pull request merged**
