### PR TITLE
Fix key stucks caused by (high) keystroke delays.

### PR DESCRIPTION
**Pull request by kareltucek**
Reproduction steps: 
- set keystrokeDelay to 60 (higher than debouncer)
- try to type
- observe stuck keys

This fixes the above and also refactors keystrokeDelay implementation so that the eventloop doesn't spin in the meantime.

Please don't merge yet. This needs a bit more thinking when I am fresh. However, feel free to start testing it.

### CODE REVIEW

**Comment by mondalaci** [comment]
Should I test on a UHK 60 or 80?

**Comment by kareltucek** [comment]
Whichever you like. I think I used uhk 80 to reproduce the problem.

**Comment by mondalaci** [comment]
I can easily reproduce the issue, and this PR fixes it. From now on, I'll test it on my UHK 60 v2.

**Comment by kareltucek** [comment]
Well I don't have any new insights about this, so feel free to merge this.

**Pull request merged**
