### PR TITLE
Send primary role modifiers consistently

### LINKED ISSUE #165: Issue with key combos as primary with a secondary roles assigned
Firmware after 8.4.1 (i.e. 8.4.1 doesn't exhibit this behaviour) seems to be having an issue if the primary role of a key is a combination and the secondary role a modifier.

For example: if I have the right alt key (that is to say the 3 key in on the bottom row on the right side) set to send super + space (that is to trigger Spotlight search on a Mac) and the secondary role to send right alt --- the super + space (the primary role) doesn't seem to be sent consistently. 

Occasionally it sends the combination but other times only seems to be sending space. Almost as if the combination is being sent too fast to register to the operation system?

If I revert to 8.4.1, I don't have the issue anymore.

### PR DESCRIPTION
**Pull request by eltang**
This closes #165.

### CODE REVIEW

**Comment by mondalaci** [comment]
This doesn't work well. Let's say that on the base layer I pick a key and set Alt+Tab as the primary role, and Alt as the secondary role. Then I tap the key. Alt+Tab triggers, but Alt stays held which shouldn't happen.

Please test your fixes in the future. Not testing them causes extra communication overhead and delays.

**Comment by eltang** [comment]
I did test this fix. The behavior you described is the one that was chosen for fixing #125. This fix doesn't change it.

**Comment by mondalaci** [comment]
I understand your reasoning, but the current behavior is clearly wrong from a usability standpoint. To make a simpler example, let's say I bind Alt+Tab to a key on the base layer. (No secondary roles are involved.) Then I tap the key, and Alt gets stuck.

I think the modifiers of a shortcut key should stick only as long as as the current layer switcher key is being held. On the base layer, no layer switcher key is held, so the modifiers of shortcuts should not stick.

**Comment by eltang** [comment]
The purpose of this PR is to ensure that a key's primary role functions the same way regardless of whether that key has a secondary role. I get that you have concerns about the behavior of sticky modifiers, but this PR doesn't touch it at all. That can be dealt with separately after this PR is merged.

**Pull request merged**
