### PR TITLE
Fix touchpad oscillation

### PR DESCRIPTION
**Pull request by kareltucek**
Please test this PR and let me know your findings.

### CODE REVIEW

**Comment by mondalaci** [comment]
According to my findings, things are working perfectly with this PR: I couldn't reproduce the oscillation issue, the touchpad pointer movement is buttery smooth, and jump to bootloader works.

That being said, I can't reproduce the oscillation with 9.1.0 either now. What are your findings regarding this PR?

**Comment by kareltucek** [comment]
According to my testing NACKs are gone and jumping to bootloader works. Refresh rate (measured at the level of the slave scheduler) is approximately 14ms, which is an improvement for both smoothness and latency.

Subjective feeling is that the latency might have gone lower (but that may be a placebo effect). Unfortunately, movement seems uneven, and seems to not follow straight lines.

**Comment by mondalaci** [comment]
I think this PR is as good as it can get. The code also looks tight, with a minor exception of an empty else clause. Given that this PR is marked as a work-in-progress, is there anything you want to improve before I merge it?

**Comment by kareltucek** [comment]
Feel free to merge then.

**Comment by cvkline** [comment]
Just downloaded this and it works a treat!  Thanks for sticking with this issue, it looks to have been a nasty one.

**Pull request merged**
