### PR TITLE
Improve OSX dependency management through brew bundle

### PR DESCRIPTION
**Pull request by stephengroat**
a new and improved osx dependency management system, takes the dependencies out of `.travis.yml` and moves them into a more track-able file

### CODE REVIEW

**Comment by mondalaci** [comment]
Thanks for your help! Unfortunately, just like the master branch, this PR fails in Travis. Can you possibly resolve this issue?

**Comment by stephengroat** [comment]
@mondalaci i looked (even tried a bump) and it seems like there's a timeout during a download.

could you try restarting the last travis job that succeeded on master to double check?

**Comment by mondalaci** [comment]
I've just restarted the last Travis job of the master branch. In any case, by looking at the commit history of the repo it's easy to notice that sometimes the build succeeds and most of the times it doesn't regardless of the state of the repo. It'd be great if the build worked consistently.

**Comment by mondalaci** [comment]
The build that was successful now errored when rebuilt, proving the inconsistency of the current build process.

**Comment by stephengroat** [comment]
`travis` is having problems with their `osx` infrastructure.

i'll look into simplifying a script for `linux`

**Comment by mondalaci** [comment]
I'm merging this in the hope that it'll make the build issues less prevalent.

**Pull request merged**
